// Code generated by go generate; DO NOT EDIT.

package model

// DOI returns the "DOI" field value.
func (item *ItemGeneric) DOI() string {
	return item.GetString("DOI")
}

// SetDOI sets the "DOI" field value.
func (item *ItemGeneric) SetDOI(val string) {
	item.Set("DOI", val)
}

// ISBN returns the "ISBN" field value.
func (item *ItemGeneric) ISBN() string {
	return item.GetString("ISBN")
}

// SetISBN sets the "ISBN" field value.
func (item *ItemGeneric) SetISBN(val string) {
	item.Set("ISBN", val)
}

// ISSN returns the "ISSN" field value.
func (item *ItemGeneric) ISSN() string {
	return item.GetString("ISSN")
}

// SetISSN sets the "ISSN" field value.
func (item *ItemGeneric) SetISSN(val string) {
	item.Set("ISSN", val)
}

// PMCID returns the "PMCID" field value.
func (item *ItemGeneric) PMCID() string {
	return item.GetString("PMCID")
}

// SetPMCID sets the "PMCID" field value.
func (item *ItemGeneric) SetPMCID(val string) {
	item.Set("PMCID", val)
}

// PMID returns the "PMID" field value.
func (item *ItemGeneric) PMID() string {
	return item.GetString("PMID")
}

// SetPMID sets the "PMID" field value.
func (item *ItemGeneric) SetPMID(val string) {
	item.Set("PMID", val)
}

// SetAbstractNote sets the "Abstract" (abstractNote) field value.
func (item *ItemGeneric) SetAbstractNote(val string) {
	item.AbstractNote = val
}

// AccessDate returns the "Accessed" (accessDate) field value.
func (item *ItemGeneric) AccessDate() string {
	return item.GetString("accessDate")
}

// SetAccessDate sets the "Accessed" (accessDate) field value.
func (item *ItemGeneric) SetAccessDate(val string) {
	item.Set("accessDate", val)
}

// ApplicationNumber returns the "Application Number" field value.
func (item *ItemGeneric) ApplicationNumber() string {
	return item.GetString("applicationNumber")
}

// SetApplicationNumber sets the "Application Number" field value.
func (item *ItemGeneric) SetApplicationNumber(val string) {
	item.Set("applicationNumber", val)
}

// Archive returns the "Archive" field value.
func (item *ItemGeneric) Archive() string {
	return item.GetString("archive")
}

// SetArchive sets the "Archive" field value.
func (item *ItemGeneric) SetArchive(val string) {
	item.Set("archive", val)
}

// ArchiveID returns the "Archive ID" field value.
func (item *ItemGeneric) ArchiveID() string {
	return item.GetString("archiveID")
}

// SetArchiveID sets the "Archive ID" field value.
func (item *ItemGeneric) SetArchiveID(val string) {
	item.Set("archiveID", val)
}

// ArchiveLocation returns the "Loc. in Archive" (archiveLocation) field value.
func (item *ItemGeneric) ArchiveLocation() string {
	return item.GetString("archiveLocation")
}

// SetArchiveLocation sets the "Loc. in Archive" (archiveLocation) field value.
func (item *ItemGeneric) SetArchiveLocation(val string) {
	item.Set("archiveLocation", val)
}

// ArtworkMedium returns the "Medium" (artworkMedium) field value.
func (item *ItemGeneric) ArtworkMedium() string {
	return item.GetString("artworkMedium")
}

// SetArtworkMedium sets the "Medium" (artworkMedium) field value.
func (item *ItemGeneric) SetArtworkMedium(val string) {
	item.Set("artworkMedium", val)
}

// ArtworkSize returns the "Artwork Size" field value.
func (item *ItemGeneric) ArtworkSize() string {
	return item.GetString("artworkSize")
}

// SetArtworkSize sets the "Artwork Size" field value.
func (item *ItemGeneric) SetArtworkSize(val string) {
	item.Set("artworkSize", val)
}

// Assignee returns the "Assignee" field value.
func (item *ItemGeneric) Assignee() string {
	return item.GetString("assignee")
}

// SetAssignee sets the "Assignee" field value.
func (item *ItemGeneric) SetAssignee(val string) {
	item.Set("assignee", val)
}

// AudioFileType returns the "File Type" (audioFileType) field value.
func (item *ItemGeneric) AudioFileType() string {
	return item.GetString("audioFileType")
}

// SetAudioFileType sets the "File Type" (audioFileType) field value.
func (item *ItemGeneric) SetAudioFileType(val string) {
	item.Set("audioFileType", val)
}

// AudioRecordingFormat returns the "Format" (audioRecordingFormat) field value.
func (item *ItemGeneric) AudioRecordingFormat() string {
	return item.GetString("audioRecordingFormat")
}

// SetAudioRecordingFormat sets the "Format" (audioRecordingFormat) field value.
func (item *ItemGeneric) SetAudioRecordingFormat(val string) {
	item.Set("audioRecordingFormat", val)
}

// BillNumber returns the "Bill Number" field value.
func (item *ItemGeneric) BillNumber() string {
	return item.GetString("billNumber")
}

// SetBillNumber sets the "Bill Number" field value.
func (item *ItemGeneric) SetBillNumber(val string) {
	item.Set("billNumber", val)
}

// BlogTitle returns the "Blog Title" field value.
func (item *ItemGeneric) BlogTitle() string {
	return item.GetString("blogTitle")
}

// SetBlogTitle sets the "Blog Title" field value.
func (item *ItemGeneric) SetBlogTitle(val string) {
	item.Set("blogTitle", val)
}

// BookTitle returns the "Book Title" field value.
func (item *ItemGeneric) BookTitle() string {
	return item.GetString("bookTitle")
}

// SetBookTitle sets the "Book Title" field value.
func (item *ItemGeneric) SetBookTitle(val string) {
	item.Set("bookTitle", val)
}

// CallNumber returns the "Call Number" field value.
func (item *ItemGeneric) CallNumber() string {
	return item.GetString("callNumber")
}

// SetCallNumber sets the "Call Number" field value.
func (item *ItemGeneric) SetCallNumber(val string) {
	item.Set("callNumber", val)
}

// CaseName returns the "Case Name" field value.
func (item *ItemGeneric) CaseName() string {
	return item.GetString("caseName")
}

// SetCaseName sets the "Case Name" field value.
func (item *ItemGeneric) SetCaseName(val string) {
	item.Set("caseName", val)
}

// SetCharset sets the "Charset" field value.
func (item *ItemGeneric) SetCharset(val string) {
	item.Charset = val
}

// CitationKey returns the "Citation Key" field value.
func (item *ItemGeneric) CitationKey() string {
	return item.GetString("citationKey")
}

// SetCitationKey sets the "Citation Key" field value.
func (item *ItemGeneric) SetCitationKey(val string) {
	item.Set("citationKey", val)
}

// Code returns the "Code" field value.
func (item *ItemGeneric) Code() string {
	return item.GetString("code")
}

// SetCode sets the "Code" field value.
func (item *ItemGeneric) SetCode(val string) {
	item.Set("code", val)
}

// CodeNumber returns the "Code Number" field value.
func (item *ItemGeneric) CodeNumber() string {
	return item.GetString("codeNumber")
}

// SetCodeNumber sets the "Code Number" field value.
func (item *ItemGeneric) SetCodeNumber(val string) {
	item.Set("codeNumber", val)
}

// CodePages returns the "Code Pages" field value.
func (item *ItemGeneric) CodePages() string {
	return item.GetString("codePages")
}

// SetCodePages sets the "Code Pages" field value.
func (item *ItemGeneric) SetCodePages(val string) {
	item.Set("codePages", val)
}

// CodeVolume returns the "Code Volume" field value.
func (item *ItemGeneric) CodeVolume() string {
	return item.GetString("codeVolume")
}

// SetCodeVolume sets the "Code Volume" field value.
func (item *ItemGeneric) SetCodeVolume(val string) {
	item.Set("codeVolume", val)
}

// Committee returns the "Committee" field value.
func (item *ItemGeneric) Committee() string {
	return item.GetString("committee")
}

// SetCommittee sets the "Committee" field value.
func (item *ItemGeneric) SetCommittee(val string) {
	item.Set("committee", val)
}

// Company returns the "Company" field value.
func (item *ItemGeneric) Company() string {
	return item.GetString("company")
}

// SetCompany sets the "Company" field value.
func (item *ItemGeneric) SetCompany(val string) {
	item.Set("company", val)
}

// ConferenceName returns the "Conference Name" field value.
func (item *ItemGeneric) ConferenceName() string {
	return item.GetString("conferenceName")
}

// SetConferenceName sets the "Conference Name" field value.
func (item *ItemGeneric) SetConferenceName(val string) {
	item.Set("conferenceName", val)
}

// SetContentType sets the "Content Type" (contentType) field value.
func (item *ItemGeneric) SetContentType(val string) {
	item.ContentType = val
}

// Country returns the "Country" field value.
func (item *ItemGeneric) Country() string {
	return item.GetString("country")
}

// SetCountry sets the "Country" field value.
func (item *ItemGeneric) SetCountry(val string) {
	item.Set("country", val)
}

// Court returns the "Court" field value.
func (item *ItemGeneric) Court() string {
	return item.GetString("court")
}

// SetCourt sets the "Court" field value.
func (item *ItemGeneric) SetCourt(val string) {
	item.Set("court", val)
}

// SetDate sets the "Date" field value.
func (item *ItemGeneric) SetDate(val string) {
	item.Date = val
}

// DateDecided returns the "Date Decided" field value.
func (item *ItemGeneric) DateDecided() string {
	return item.GetString("dateDecided")
}

// SetDateDecided sets the "Date Decided" field value.
func (item *ItemGeneric) SetDateDecided(val string) {
	item.Set("dateDecided", val)
}

// DateEnacted returns the "Date Enacted" field value.
func (item *ItemGeneric) DateEnacted() string {
	return item.GetString("dateEnacted")
}

// SetDateEnacted sets the "Date Enacted" field value.
func (item *ItemGeneric) SetDateEnacted(val string) {
	item.Set("dateEnacted", val)
}

// DictionaryTitle returns the "Dictionary Title" field value.
func (item *ItemGeneric) DictionaryTitle() string {
	return item.GetString("dictionaryTitle")
}

// SetDictionaryTitle sets the "Dictionary Title" field value.
func (item *ItemGeneric) SetDictionaryTitle(val string) {
	item.Set("dictionaryTitle", val)
}

// Distributor returns the "Distributor" field value.
func (item *ItemGeneric) Distributor() string {
	return item.GetString("distributor")
}

// SetDistributor sets the "Distributor" field value.
func (item *ItemGeneric) SetDistributor(val string) {
	item.Set("distributor", val)
}

// DocketNumber returns the "Docket Number" field value.
func (item *ItemGeneric) DocketNumber() string {
	return item.GetString("docketNumber")
}

// SetDocketNumber sets the "Docket Number" field value.
func (item *ItemGeneric) SetDocketNumber(val string) {
	item.Set("docketNumber", val)
}

// DocumentNumber returns the "Document Number" field value.
func (item *ItemGeneric) DocumentNumber() string {
	return item.GetString("documentNumber")
}

// SetDocumentNumber sets the "Document Number" field value.
func (item *ItemGeneric) SetDocumentNumber(val string) {
	item.Set("documentNumber", val)
}

// Edition returns the "Edition" field value.
func (item *ItemGeneric) Edition() string {
	return item.GetString("edition")
}

// SetEdition sets the "Edition" field value.
func (item *ItemGeneric) SetEdition(val string) {
	item.Set("edition", val)
}

// EncyclopediaTitle returns the "Encyclopedia Title" field value.
func (item *ItemGeneric) EncyclopediaTitle() string {
	return item.GetString("encyclopediaTitle")
}

// SetEncyclopediaTitle sets the "Encyclopedia Title" field value.
func (item *ItemGeneric) SetEncyclopediaTitle(val string) {
	item.Set("encyclopediaTitle", val)
}

// EpisodeNumber returns the "Episode Number" field value.
func (item *ItemGeneric) EpisodeNumber() string {
	return item.GetString("episodeNumber")
}

// SetEpisodeNumber sets the "Episode Number" field value.
func (item *ItemGeneric) SetEpisodeNumber(val string) {
	item.Set("episodeNumber", val)
}

// EventPlace returns the "Event Place" field value.
func (item *ItemGeneric) EventPlace() string {
	return item.GetString("eventPlace")
}

// SetEventPlace sets the "Event Place" field value.
func (item *ItemGeneric) SetEventPlace(val string) {
	item.Set("eventPlace", val)
}

// SetExtra sets the "Extra" field value.
func (item *ItemGeneric) SetExtra(val string) {
	item.Extra = val
}

// SetFilename sets the "Filename" field value.
func (item *ItemGeneric) SetFilename(val string) {
	item.Filename = val
}

// FilingDate returns the "Filing Date" field value.
func (item *ItemGeneric) FilingDate() string {
	return item.GetString("filingDate")
}

// SetFilingDate sets the "Filing Date" field value.
func (item *ItemGeneric) SetFilingDate(val string) {
	item.Set("filingDate", val)
}

// FirstPage returns the "First Page" field value.
func (item *ItemGeneric) FirstPage() string {
	return item.GetString("firstPage")
}

// SetFirstPage sets the "First Page" field value.
func (item *ItemGeneric) SetFirstPage(val string) {
	item.Set("firstPage", val)
}

// Format returns the "Format" field value.
func (item *ItemGeneric) Format() string {
	return item.GetString("format")
}

// SetFormat sets the "Format" field value.
func (item *ItemGeneric) SetFormat(val string) {
	item.Set("format", val)
}

// ForumTitle returns the "Forum/Listserv Title" (forumTitle) field value.
func (item *ItemGeneric) ForumTitle() string {
	return item.GetString("forumTitle")
}

// SetForumTitle sets the "Forum/Listserv Title" (forumTitle) field value.
func (item *ItemGeneric) SetForumTitle(val string) {
	item.Set("forumTitle", val)
}

// Genre returns the "Genre" field value.
func (item *ItemGeneric) Genre() string {
	return item.GetString("genre")
}

// SetGenre sets the "Genre" field value.
func (item *ItemGeneric) SetGenre(val string) {
	item.Set("genre", val)
}

// History returns the "History" field value.
func (item *ItemGeneric) History() string {
	return item.GetString("history")
}

// SetHistory sets the "History" field value.
func (item *ItemGeneric) SetHistory(val string) {
	item.Set("history", val)
}

// Identifier returns the "Identifier" field value.
func (item *ItemGeneric) Identifier() string {
	return item.GetString("identifier")
}

// SetIdentifier sets the "Identifier" field value.
func (item *ItemGeneric) SetIdentifier(val string) {
	item.Set("identifier", val)
}

// Institution returns the "Institution" field value.
func (item *ItemGeneric) Institution() string {
	return item.GetString("institution")
}

// SetInstitution sets the "Institution" field value.
func (item *ItemGeneric) SetInstitution(val string) {
	item.Set("institution", val)
}

// InterviewMedium returns the "Medium" (interviewMedium) field value.
func (item *ItemGeneric) InterviewMedium() string {
	return item.GetString("interviewMedium")
}

// SetInterviewMedium sets the "Medium" (interviewMedium) field value.
func (item *ItemGeneric) SetInterviewMedium(val string) {
	item.Set("interviewMedium", val)
}

// Issue returns the "Issue" field value.
func (item *ItemGeneric) Issue() string {
	return item.GetString("issue")
}

// SetIssue sets the "Issue" field value.
func (item *ItemGeneric) SetIssue(val string) {
	item.Set("issue", val)
}

// IssueDate returns the "Issue Date" field value.
func (item *ItemGeneric) IssueDate() string {
	return item.GetString("issueDate")
}

// SetIssueDate sets the "Issue Date" field value.
func (item *ItemGeneric) SetIssueDate(val string) {
	item.Set("issueDate", val)
}

// IssuingAuthority returns the "Issuing Authority" field value.
func (item *ItemGeneric) IssuingAuthority() string {
	return item.GetString("issuingAuthority")
}

// SetIssuingAuthority sets the "Issuing Authority" field value.
func (item *ItemGeneric) SetIssuingAuthority(val string) {
	item.Set("issuingAuthority", val)
}

// JournalAbbreviation returns the "Journal Abbr" (journalAbbreviation) field value.
func (item *ItemGeneric) JournalAbbreviation() string {
	return item.GetString("journalAbbreviation")
}

// SetJournalAbbreviation sets the "Journal Abbr" (journalAbbreviation) field value.
func (item *ItemGeneric) SetJournalAbbreviation(val string) {
	item.Set("journalAbbreviation", val)
}

// Label returns the "Label" field value.
func (item *ItemGeneric) Label() string {
	return item.GetString("label")
}

// SetLabel sets the "Label" field value.
func (item *ItemGeneric) SetLabel(val string) {
	item.Set("label", val)
}

// Language returns the "Language" field value.
func (item *ItemGeneric) Language() string {
	return item.GetString("language")
}

// SetLanguage sets the "Language" field value.
func (item *ItemGeneric) SetLanguage(val string) {
	item.Set("language", val)
}

// LegalStatus returns the "Legal Status" field value.
func (item *ItemGeneric) LegalStatus() string {
	return item.GetString("legalStatus")
}

// SetLegalStatus sets the "Legal Status" field value.
func (item *ItemGeneric) SetLegalStatus(val string) {
	item.Set("legalStatus", val)
}

// LegislativeBody returns the "Legislative Body" field value.
func (item *ItemGeneric) LegislativeBody() string {
	return item.GetString("legislativeBody")
}

// SetLegislativeBody sets the "Legislative Body" field value.
func (item *ItemGeneric) SetLegislativeBody(val string) {
	item.Set("legislativeBody", val)
}

// LetterType returns the "Type" (letterType) field value.
func (item *ItemGeneric) LetterType() string {
	return item.GetString("letterType")
}

// SetLetterType sets the "Type" (letterType) field value.
func (item *ItemGeneric) SetLetterType(val string) {
	item.Set("letterType", val)
}

// LibraryCatalog returns the "Library Catalog" field value.
func (item *ItemGeneric) LibraryCatalog() string {
	return item.GetString("libraryCatalog")
}

// SetLibraryCatalog sets the "Library Catalog" field value.
func (item *ItemGeneric) SetLibraryCatalog(val string) {
	item.Set("libraryCatalog", val)
}

// SetLinkMode sets the "Link Mode" (linkMode) field value.
func (item *ItemGeneric) SetLinkMode(val string) {
	item.LinkMode = val
}

// ManuscriptType returns the "Type" (manuscriptType) field value.
func (item *ItemGeneric) ManuscriptType() string {
	return item.GetString("manuscriptType")
}

// SetManuscriptType sets the "Type" (manuscriptType) field value.
func (item *ItemGeneric) SetManuscriptType(val string) {
	item.Set("manuscriptType", val)
}

// MapType returns the "Type" (mapType) field value.
func (item *ItemGeneric) MapType() string {
	return item.GetString("mapType")
}

// SetMapType sets the "Type" (mapType) field value.
func (item *ItemGeneric) SetMapType(val string) {
	item.Set("mapType", val)
}

// SetMD5 sets the "MD5" field value.
func (item *ItemGeneric) SetMD5(val string) {
	item.MD5 = val
}

// MeetingName returns the "Meeting Name" field value.
func (item *ItemGeneric) MeetingName() string {
	return item.GetString("meetingName")
}

// SetMeetingName sets the "Meeting Name" field value.
func (item *ItemGeneric) SetMeetingName(val string) {
	item.Set("meetingName", val)
}

// NameOfAct returns the "Name of Act" field value.
func (item *ItemGeneric) NameOfAct() string {
	return item.GetString("nameOfAct")
}

// SetNameOfAct sets the "Name of Act" field value.
func (item *ItemGeneric) SetNameOfAct(val string) {
	item.Set("nameOfAct", val)
}

// Network returns the "Network" field value.
func (item *ItemGeneric) Network() string {
	return item.GetString("network")
}

// SetNetwork sets the "Network" field value.
func (item *ItemGeneric) SetNetwork(val string) {
	item.Set("network", val)
}

// SetNote sets the "note" field value.
func (item *ItemGeneric) SetNote(val string) {
	item.Note = val
}

// NumPages returns the "# of Pages" (numPages) field value.
func (item *ItemGeneric) NumPages() string {
	return item.GetString("numPages")
}

// SetNumPages sets the "# of Pages" (numPages) field value.
func (item *ItemGeneric) SetNumPages(val string) {
	item.Set("numPages", val)
}

// Number returns the "Number" field value.
func (item *ItemGeneric) Number() string {
	return item.GetString("number")
}

// SetNumber sets the "Number" field value.
func (item *ItemGeneric) SetNumber(val string) {
	item.Set("number", val)
}

// NumberOfVolumes returns the "# of Volumes" (numberOfVolumes) field value.
func (item *ItemGeneric) NumberOfVolumes() string {
	return item.GetString("numberOfVolumes")
}

// SetNumberOfVolumes sets the "# of Volumes" (numberOfVolumes) field value.
func (item *ItemGeneric) SetNumberOfVolumes(val string) {
	item.Set("numberOfVolumes", val)
}

// Organization returns the "Organization" field value.
func (item *ItemGeneric) Organization() string {
	return item.GetString("organization")
}

// SetOrganization sets the "Organization" field value.
func (item *ItemGeneric) SetOrganization(val string) {
	item.Set("organization", val)
}

// OriginalDate returns the "Original Date" field value.
func (item *ItemGeneric) OriginalDate() string {
	return item.GetString("originalDate")
}

// SetOriginalDate sets the "Original Date" field value.
func (item *ItemGeneric) SetOriginalDate(val string) {
	item.Set("originalDate", val)
}

// OriginalPlace returns the "Original Place" field value.
func (item *ItemGeneric) OriginalPlace() string {
	return item.GetString("originalPlace")
}

// SetOriginalPlace sets the "Original Place" field value.
func (item *ItemGeneric) SetOriginalPlace(val string) {
	item.Set("originalPlace", val)
}

// OriginalPublisher returns the "Original Publisher" field value.
func (item *ItemGeneric) OriginalPublisher() string {
	return item.GetString("originalPublisher")
}

// SetOriginalPublisher sets the "Original Publisher" field value.
func (item *ItemGeneric) SetOriginalPublisher(val string) {
	item.Set("originalPublisher", val)
}

// Pages returns the "Pages" field value.
func (item *ItemGeneric) Pages() string {
	return item.GetString("pages")
}

// SetPages sets the "Pages" field value.
func (item *ItemGeneric) SetPages(val string) {
	item.Set("pages", val)
}

// PartNumber returns the "Part Number" field value.
func (item *ItemGeneric) PartNumber() string {
	return item.GetString("partNumber")
}

// SetPartNumber sets the "Part Number" field value.
func (item *ItemGeneric) SetPartNumber(val string) {
	item.Set("partNumber", val)
}

// PartTitle returns the "Part Title" field value.
func (item *ItemGeneric) PartTitle() string {
	return item.GetString("partTitle")
}

// SetPartTitle sets the "Part Title" field value.
func (item *ItemGeneric) SetPartTitle(val string) {
	item.Set("partTitle", val)
}

// PatentNumber returns the "Patent Number" field value.
func (item *ItemGeneric) PatentNumber() string {
	return item.GetString("patentNumber")
}

// SetPatentNumber sets the "Patent Number" field value.
func (item *ItemGeneric) SetPatentNumber(val string) {
	item.Set("patentNumber", val)
}

// Place returns the "Place" field value.
func (item *ItemGeneric) Place() string {
	return item.GetString("place")
}

// SetPlace sets the "Place" field value.
func (item *ItemGeneric) SetPlace(val string) {
	item.Set("place", val)
}

// PostType returns the "Post Type" field value.
func (item *ItemGeneric) PostType() string {
	return item.GetString("postType")
}

// SetPostType sets the "Post Type" field value.
func (item *ItemGeneric) SetPostType(val string) {
	item.Set("postType", val)
}

// PresentationType returns the "Type" (presentationType) field value.
func (item *ItemGeneric) PresentationType() string {
	return item.GetString("presentationType")
}

// SetPresentationType sets the "Type" (presentationType) field value.
func (item *ItemGeneric) SetPresentationType(val string) {
	item.Set("presentationType", val)
}

// PriorityDate returns the "Priority Date" field value.
func (item *ItemGeneric) PriorityDate() string {
	return item.GetString("priorityDate")
}

// SetPriorityDate sets the "Priority Date" field value.
func (item *ItemGeneric) SetPriorityDate(val string) {
	item.Set("priorityDate", val)
}

// PriorityNumbers returns the "Priority Numbers" field value.
func (item *ItemGeneric) PriorityNumbers() string {
	return item.GetString("priorityNumbers")
}

// SetPriorityNumbers sets the "Priority Numbers" field value.
func (item *ItemGeneric) SetPriorityNumbers(val string) {
	item.Set("priorityNumbers", val)
}

// ProceedingsTitle returns the "Proceedings Title" field value.
func (item *ItemGeneric) ProceedingsTitle() string {
	return item.GetString("proceedingsTitle")
}

// SetProceedingsTitle sets the "Proceedings Title" field value.
func (item *ItemGeneric) SetProceedingsTitle(val string) {
	item.Set("proceedingsTitle", val)
}

// ProgramTitle returns the "Program Title" field value.
func (item *ItemGeneric) ProgramTitle() string {
	return item.GetString("programTitle")
}

// SetProgramTitle sets the "Program Title" field value.
func (item *ItemGeneric) SetProgramTitle(val string) {
	item.Set("programTitle", val)
}

// ProgrammingLanguage returns the "Prog. Language" (programmingLanguage) field value.
func (item *ItemGeneric) ProgrammingLanguage() string {
	return item.GetString("programmingLanguage")
}

// SetProgrammingLanguage sets the "Prog. Language" (programmingLanguage) field value.
func (item *ItemGeneric) SetProgrammingLanguage(val string) {
	item.Set("programmingLanguage", val)
}

// PublicLawNumber returns the "Public Law Number" field value.
func (item *ItemGeneric) PublicLawNumber() string {
	return item.GetString("publicLawNumber")
}

// SetPublicLawNumber sets the "Public Law Number" field value.
func (item *ItemGeneric) SetPublicLawNumber(val string) {
	item.Set("publicLawNumber", val)
}

// PublicationTitle returns the "Publication" (publicationTitle) field value.
func (item *ItemGeneric) PublicationTitle() string {
	return item.GetString("publicationTitle")
}

// SetPublicationTitle sets the "Publication" (publicationTitle) field value.
func (item *ItemGeneric) SetPublicationTitle(val string) {
	item.Set("publicationTitle", val)
}

// Publisher returns the "Publisher" field value.
func (item *ItemGeneric) Publisher() string {
	return item.GetString("publisher")
}

// SetPublisher sets the "Publisher" field value.
func (item *ItemGeneric) SetPublisher(val string) {
	item.Set("publisher", val)
}

// References returns the "References" field value.
func (item *ItemGeneric) References() string {
	return item.GetString("references")
}

// SetReferences sets the "References" field value.
func (item *ItemGeneric) SetReferences(val string) {
	item.Set("references", val)
}

// ReportNumber returns the "Report Number" field value.
func (item *ItemGeneric) ReportNumber() string {
	return item.GetString("reportNumber")
}

// SetReportNumber sets the "Report Number" field value.
func (item *ItemGeneric) SetReportNumber(val string) {
	item.Set("reportNumber", val)
}

// ReportType returns the "Report Type" field value.
func (item *ItemGeneric) ReportType() string {
	return item.GetString("reportType")
}

// SetReportType sets the "Report Type" field value.
func (item *ItemGeneric) SetReportType(val string) {
	item.Set("reportType", val)
}

// Reporter returns the "Reporter" field value.
func (item *ItemGeneric) Reporter() string {
	return item.GetString("reporter")
}

// SetReporter sets the "Reporter" field value.
func (item *ItemGeneric) SetReporter(val string) {
	item.Set("reporter", val)
}

// ReporterVolume returns the "Reporter Volume" field value.
func (item *ItemGeneric) ReporterVolume() string {
	return item.GetString("reporterVolume")
}

// SetReporterVolume sets the "Reporter Volume" field value.
func (item *ItemGeneric) SetReporterVolume(val string) {
	item.Set("reporterVolume", val)
}

// Repository returns the "Repository" field value.
func (item *ItemGeneric) Repository() string {
	return item.GetString("repository")
}

// SetRepository sets the "Repository" field value.
func (item *ItemGeneric) SetRepository(val string) {
	item.Set("repository", val)
}

// RepositoryLocation returns the "Repo. Location" (repositoryLocation) field value.
func (item *ItemGeneric) RepositoryLocation() string {
	return item.GetString("repositoryLocation")
}

// SetRepositoryLocation sets the "Repo. Location" (repositoryLocation) field value.
func (item *ItemGeneric) SetRepositoryLocation(val string) {
	item.Set("repositoryLocation", val)
}

// Rights returns the "License" (rights) field value.
func (item *ItemGeneric) Rights() string {
	return item.GetString("rights")
}

// SetRights sets the "License" (rights) field value.
func (item *ItemGeneric) SetRights(val string) {
	item.Set("rights", val)
}

// RunningTime returns the "Running Time" field value.
func (item *ItemGeneric) RunningTime() string {
	return item.GetString("runningTime")
}

// SetRunningTime sets the "Running Time" field value.
func (item *ItemGeneric) SetRunningTime(val string) {
	item.Set("runningTime", val)
}

// Scale returns the "Scale" field value.
func (item *ItemGeneric) Scale() string {
	return item.GetString("scale")
}

// SetScale sets the "Scale" field value.
func (item *ItemGeneric) SetScale(val string) {
	item.Set("scale", val)
}

// Section returns the "Section" field value.
func (item *ItemGeneric) Section() string {
	return item.GetString("section")
}

// SetSection sets the "Section" field value.
func (item *ItemGeneric) SetSection(val string) {
	item.Set("section", val)
}

// Series returns the "Series" field value.
func (item *ItemGeneric) Series() string {
	return item.GetString("series")
}

// SetSeries sets the "Series" field value.
func (item *ItemGeneric) SetSeries(val string) {
	item.Set("series", val)
}

// SeriesNumber returns the "Series Number" field value.
func (item *ItemGeneric) SeriesNumber() string {
	return item.GetString("seriesNumber")
}

// SetSeriesNumber sets the "Series Number" field value.
func (item *ItemGeneric) SetSeriesNumber(val string) {
	item.Set("seriesNumber", val)
}

// SeriesText returns the "Series Text" field value.
func (item *ItemGeneric) SeriesText() string {
	return item.GetString("seriesText")
}

// SetSeriesText sets the "Series Text" field value.
func (item *ItemGeneric) SetSeriesText(val string) {
	item.Set("seriesText", val)
}

// SeriesTitle returns the "Series Title" field value.
func (item *ItemGeneric) SeriesTitle() string {
	return item.GetString("seriesTitle")
}

// SetSeriesTitle sets the "Series Title" field value.
func (item *ItemGeneric) SetSeriesTitle(val string) {
	item.Set("seriesTitle", val)
}

// Session returns the "Session" field value.
func (item *ItemGeneric) Session() string {
	return item.GetString("session")
}

// SetSession sets the "Session" field value.
func (item *ItemGeneric) SetSession(val string) {
	item.Set("session", val)
}

// SessionTitle returns the "Session Title" field value.
func (item *ItemGeneric) SessionTitle() string {
	return item.GetString("sessionTitle")
}

// SetSessionTitle sets the "Session Title" field value.
func (item *ItemGeneric) SetSessionTitle(val string) {
	item.Set("sessionTitle", val)
}

// SetShortTitle sets the "Short Title" field value.
func (item *ItemGeneric) SetShortTitle(val string) {
	item.ShortTitle = val
}

// Status returns the "Status" field value.
func (item *ItemGeneric) Status() string {
	return item.GetString("status")
}

// SetStatus sets the "Status" field value.
func (item *ItemGeneric) SetStatus(val string) {
	item.Set("status", val)
}

// Studio returns the "Studio" field value.
func (item *ItemGeneric) Studio() string {
	return item.GetString("studio")
}

// SetStudio sets the "Studio" field value.
func (item *ItemGeneric) SetStudio(val string) {
	item.Set("studio", val)
}

// Subject returns the "Subject" field value.
func (item *ItemGeneric) Subject() string {
	return item.GetString("subject")
}

// SetSubject sets the "Subject" field value.
func (item *ItemGeneric) SetSubject(val string) {
	item.Set("subject", val)
}

// System returns the "System" field value.
func (item *ItemGeneric) System() string {
	return item.GetString("system")
}

// SetSystem sets the "System" field value.
func (item *ItemGeneric) SetSystem(val string) {
	item.Set("system", val)
}

// ThesisType returns the "Type" (thesisType) field value.
func (item *ItemGeneric) ThesisType() string {
	return item.GetString("thesisType")
}

// SetThesisType sets the "Type" (thesisType) field value.
func (item *ItemGeneric) SetThesisType(val string) {
	item.Set("thesisType", val)
}

// SetTitle sets the "Title" field value.
func (item *ItemGeneric) SetTitle(val string) {
	item.Title = val
}

// Type returns the "Type" field value.
func (item *ItemGeneric) Type() string {
	return item.GetString("type")
}

// SetType sets the "Type" field value.
func (item *ItemGeneric) SetType(val string) {
	item.Set("type", val)
}

// University returns the "University" field value.
func (item *ItemGeneric) University() string {
	return item.GetString("university")
}

// SetUniversity sets the "University" field value.
func (item *ItemGeneric) SetUniversity(val string) {
	item.Set("university", val)
}

// SetUrl sets the "URL" field value.
func (item *ItemGeneric) SetUrl(val string) {
	item.Url = val
}

// VersionNumber returns the "Version" (versionNumber) field value.
func (item *ItemGeneric) VersionNumber() string {
	return item.GetString("versionNumber")
}

// SetVersionNumber sets the "Version" (versionNumber) field value.
func (item *ItemGeneric) SetVersionNumber(val string) {
	item.Set("versionNumber", val)
}

// VideoRecordingFormat returns the "Format" (videoRecordingFormat) field value.
func (item *ItemGeneric) VideoRecordingFormat() string {
	return item.GetString("videoRecordingFormat")
}

// SetVideoRecordingFormat sets the "Format" (videoRecordingFormat) field value.
func (item *ItemGeneric) SetVideoRecordingFormat(val string) {
	item.Set("videoRecordingFormat", val)
}

// Volume returns the "Volume" field value.
func (item *ItemGeneric) Volume() string {
	return item.GetString("volume")
}

// SetVolume sets the "Volume" field value.
func (item *ItemGeneric) SetVolume(val string) {
	item.Set("volume", val)
}

// WebsiteTitle returns the "Website Title" field value.
func (item *ItemGeneric) WebsiteTitle() string {
	return item.GetString("websiteTitle")
}

// SetWebsiteTitle sets the "Website Title" field value.
func (item *ItemGeneric) SetWebsiteTitle(val string) {
	item.Set("websiteTitle", val)
}

// WebsiteType returns the "Website Type" field value.
func (item *ItemGeneric) WebsiteType() string {
	return item.GetString("websiteType")
}

// SetWebsiteType sets the "Website Type" field value.
func (item *ItemGeneric) SetWebsiteType(val string) {
	item.Set("websiteType", val)
}
